version: '3'

services:
 app:
   build:
     context: .

   ports:
     - "8000:8000"
   volumes:
     - ./:/upprpo
   command:
     sh -c "python manage.py test main; python manage.py test chat; python manage.py runserver 0.0.0.0:8000"