# Generated by Django 4.0.3 on 2022-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_set',
            field=models.ManyToManyField(to='chat.message'),
        ),
    ]
