# Generated by Django 4.0.3 on 2022-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameHtml5',
            fields=[
                ('src', models.CharField(max_length=500)),
                ('genre', models.CharField(choices=[('arcade', 'arcade')], max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/no-image.jpg', upload_to='images/')),
            ],
        ),
    ]
